"lots o change"

diff --git a/zsh/functions/mkall b/zsh/functions/mkall
--- a/zsh/functions/mkall
+++ b/zsh/functions/mkall
@@ -6,107 +6,116 @@
 # function that handles the most basic and common of build processes
 
 function mkall () {
-	while getopts "c:n:s:" opts; do
+	while getopts "cntC:" opts; do
 		case $opts in 
 
-			n) export skip=false
-				 ninja_opt=true
+			n ) 
+         export skip=true
+				 export check_type='skip'
 				 ;;
 
-			c) export skip=false
-				 export check_opt="$OPTARG"
+			t ) 
+         export skip=false
+				 export check_type='test'
 				 ;;
 
-		 \?) printf '\n\n\e[31mUnrecognized options passed. Aborting!\e[0m\n' 
-				 printf 'Usage: %s <-(t)est|(c)heck|(n)o-test> \n\n\n' "$0"
+			c ) 
+         export skip=false
+				 export check_type='check'
+				 ;;
+
+      C ) 
+         export skip=false
+         export check_type="custom"
+         export args="$OPTARG"
+         ;;
+      ? )
+         printf '\n\n\e[31mUnrecognized options passed. Aborting!\e[0m\n' 
+				 printf 'Usage: %s < (-t)est|(-c)heck|(-n)o-test > \n\n\n' "$0"
 				 sleep 2
 				 return 1
 				 ;;
 	  esac
 	done
-	
-	function ok () {
-		sleep 1
-		printf '\n\n[ \e[32mOK\e[0m ]\n'
-		sleep 1
-	}
 
-	function pass () {
-		sleep 1
-		printf '\n\n[ \e[32mPASS\e[0m ]\n'
-		sleep 1
-	}
+  function log () {
+    log_type=$1
 
-	function fail_out () {
-		sleep 1
-		printf '\n\n[ \e[31mFAIL\e[0m ]\n' 
-		sleep 3
-		exit 1
-	}
+    msg_ok='\n\n[ \e[32mOK\e[0m ]\n'
+	  msg_pass='\n\n[ \e[32mPASS\e[0m ]\n'
+    msg_fail='\n\n[ \e[31mFAIL\e[0m ]\n'
+    msg_test='\n\n\n[ \e[31;1mTESTING\e[0m ]\n\n\n\n'
+    msg_check='\n\n\n[ \e[32;1mCHECKING\e[0m ]\n\n\n\n'
+    msg_skip='\n\n\n[ \e[1;33;1mSKIPPING TEST-SUITES...\e[0m ]\n\n\n\n'
+
+    sleep 1
+    case $log_type in 
+      'ok' )
+        printf %s $msg_ok
+        ;;
+      'pass' )
+        printf %s $msg_pass
+        ;;
+      'fail' ) 
+        printf %s $msg_fail
+        sleep 2
+        ;;
+      'test' ) 
+        printf %s $msg_test
+        ;;
+      'check' ) 
+        printf %s $msg_check
+        ;;
+      'skip' ) 
+        printf %s $msg_test
+        ;;
+      * )
+        echo "Uknown error; aborting!"
+        exit 0
+        ;;
+    esac
+    sleep 2
+    unset log_type msg_{ok,pass,fail,test,check,skip}
+  }
 
 	function test_suite () {
-		sleep 1
-		printf '\n\n\n\e[31;1mTESTING...\e[0m\n\n\n\n'
-		sleep 1
-		make test
-	}
-	
-	function check_suite () {
-		sleep 1
-		printf '\n\n\n\e[32;1mCHECKING...\e[0m\n\n\n\n'
-		sleep 1
-		make check
-	}
-	
-	function skip_suite () {
-		sleep 1
-		printf '\n\n\n\e[1;33;1mSKIPPING TEST-SUITES...\e[0m\n\n\n\n'
-		sleep 1
-	}
+    log $check_type
+	  # test build
+	  if [ "$skip" ]; then
+	  	export ret_val=0
+      log 'ok'
+	  else
+	  	if [ "$check_type" = 'test' ]; then
+        make test
+	  		export ret_val=${?}
+        log 'ok'
+      elif [ "$check_type" = 'check']; then
+	  		make check
+	  		export ret_val=${?}
+        log 'ok'
+	  	fi
+	  fi
 
+	  # checks tests
+	  if [ "$ret_val" -gt 0 ] ; then 
+	  	printf '\nStatus indicates a failure during tests. Continue anyway?\n(n/Y)  '
+	  	read -r -n1 check
+	  	sleep 1
+	  	if [ "$check" = 'n' ]; then
+        log 'fail' && exit 1
+	  	fi
+	  fi
+	}
 
 	# start build
-	make || fail_out
-	pass
-
-	# test build
-	if [ "$skip" ]; then
-		skip_suite
-		export r=$?
-	else
-		if [ "$opt" ]; then
-			test_suite
-			export r=$?
-		else
-			check_suite
-			export r=$?
-		fi
-	fi
-
-	# checks tests
-	if [ "$r" -gt 0 ] ; then 
-
-		printf '\nStatus indicates a failure during tests. Continue anyway?\n(n/Y)  '
-		read -r -n1 check
-		sleep 1
-
-
-		if [ "$check" = 'n' ]; then
-
-			printf 'Aborting, make {,dist}clean (<- joke) may be needed\n\n'
-			return 1
-
-		fi
-	fi
-	pass
-
-	unset skip check opt r
-
+  (make && log 'pass') || (log 'fail' && exit 1)
+  #test
+  (test_suite && log 'pass') || (log 'fail' && exit 1)
 	# installs build
-	sudo make install || fail_out
-	pass
-
+  (sudo make install && log 'pass') || (log 'fail' && exit 1)
+  # return to sources directory
 	cd $HOME/.local/src
-
+  # clear variables
+	unset skip check check_type ret_val
 }
 
